/**
 * LEVEL Icon Map
 * Centralised registry of every platform icon with its Lucide source,
 * display label, gradient variant, and placement context.
 */
import {
  User,
  BadgeCheck,
  HeartHandshake,
  GitMerge,
  MessageSquare,
  MessageCircle,
  Heart,
  Calendar,
  UtensilsCrossed,
  MapPin,
  SlidersHorizontal,
  Bell,
  Gem,
  ShieldCheck,
  ConciergeBell,
  CalendarCheck,
  UserPlus,
  Target,
  Briefcase,
  HeartPulse,
} from 'lucide-react'

export const LEVEL_ICONS = [
  { id: 'profile',       icon: User,             label: 'Profile',              gradient: 'primary' },
  { id: 'verified',      icon: BadgeCheck,        label: 'Verified',             gradient: 'ocean'   },
  { id: 'matchmaking',   icon: HeartHandshake,    label: 'Matchmaking',          gradient: 'primary' },
  { id: 'compatibility', icon: GitMerge,          label: 'Compatibility',        gradient: 'ocean'   },
  { id: 'chat',          icon: MessageSquare,     label: 'Chat',                 gradient: 'primary' },
  { id: 'message',       icon: MessageCircle,     label: 'Message Request',      gradient: 'soft'    },
  { id: 'heart',         icon: Heart,             label: 'Heart',                gradient: 'primary' },
  { id: 'calendar',      icon: Calendar,          label: 'Calendar',             gradient: 'ocean'   },
  { id: 'restaurant',    icon: UtensilsCrossed,   label: 'Restaurant',           gradient: 'primary' },
  { id: 'location',      icon: MapPin,            label: 'Location',             gradient: 'ocean'   },
  { id: 'settings',      icon: SlidersHorizontal, label: 'Settings',             gradient: 'primary' },
  { id: 'notification',  icon: Bell,              label: 'Notification',         gradient: 'soft'    },
  { id: 'premium',       icon: Gem,               label: 'Premium',              gradient: 'gold'    },
  { id: 'security',      icon: ShieldCheck,       label: 'Security',             gradient: 'primary' },
  { id: 'concierge',     icon: ConciergeBell,     label: 'Concierge',            gradient: 'gold'    },
  { id: 'datebook',      icon: CalendarCheck,     label: 'Date Booking',         gradient: 'ocean'   },
  { id: 'connection',    icon: UserPlus,          label: 'Connection',           gradient: 'primary' },
  { id: 'goals',         icon: Target,            label: 'Relationship Goals',   gradient: 'soft'    },
  { id: 'career',        icon: Briefcase,         label: 'Career Alignment',     gradient: 'ocean'   },
  { id: 'emotional',     icon: HeartPulse,        label: 'Emotional Compat.',    gradient: 'primary' },
]

/* Named re-exports for per-component imports */
export {
  User          as ProfileIcon,
  BadgeCheck    as VerifiedIcon,
  HeartHandshake as MatchmakingIcon,
  GitMerge      as CompatibilityIcon,
  MessageSquare as ChatIcon,
  MessageCircle as MessageIcon,
  Heart         as HeartIcon,
  Calendar      as CalendarIcon,
  UtensilsCrossed as RestaurantIcon,
  MapPin        as LocationIcon,
  SlidersHorizontal as SettingsIcon,
  Bell          as NotificationIcon,
  Gem           as PremiumIcon,
  ShieldCheck   as SecurityIcon,
  ConciergeBell as ConciergeIcon,
  CalendarCheck as DateBookingIcon,
  UserPlus      as ConnectionIcon,
  Target        as GoalsIcon,
  Briefcase     as CareerIcon,
  HeartPulse    as EmotionalIcon,
}
