const { validate: uuidValidate, version: uuidVersion } = require('uuid')

/**
 * Enforces a valid UUIDv4 Idempotency-Key header on every payment mutation.
 *
 * Rejects before touching any payment logic so duplicate clicks, network
 * retries, and timeout re-sends are filtered at the edge. The validated key
 * is attached to req.idempotencyKey for downstream use in the ledger INSERT.
 */
function requireIdempotencyKey(req, res, next) {
  const key = req.headers['idempotency-key']

  if (!key) {
    return res.status(400).json({
      error:   'MISSING_IDEMPOTENCY_KEY',
      message: 'A unique UUIDv4 Idempotency-Key header is required for all payment write requests.',
    })
  }

  if (!uuidValidate(key) || uuidVersion(key) !== 4) {
    return res.status(400).json({
      error:   'INVALID_IDEMPOTENCY_KEY',
      message: 'Idempotency-Key must be a valid UUIDv4 string (e.g. generated by crypto.randomUUID()).',
    })
  }

  req.idempotencyKey = key
  next()
}

module.exports = { requireIdempotencyKey }
